name: /new_home/Software/anaconda3/zh
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2024.3.11=h06a4308_0
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.0=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=69.5.1=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - alembic==1.14.1
    - annotated-types==0.7.0
    - axial-positional-embedding==0.2.1
    - certifi==2024.7.4
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cmake==4.1.0
    - colorlog==6.9.0
    - conda-pack==0.8.1
    - contourpy==1.1.1
    - cycler==0.12.1
    - deprecated==1.2.14
    - docker-pycreds==0.4.0
    - einops==0.4.0
    - filelock==3.15.4
    - fire==0.7.1
    - fonttools==4.53.1
    - fsspec==2024.6.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - gluonts==0.15.1
    - greenlet==3.1.1
    - idna==3.7
    - importlib-metadata==8.0.0
    - importlib-resources==6.4.0
    - jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - lightning-utilities==0.11.9
    - linear-attention-transformer==0.19.1
    - linformer==0.2.3
    - lit==18.1.8
    - llvmlite==0.41.1
    - local-attention==1.4.4
    - mako==1.3.10
    - markupsafe==2.1.5
    - matplotlib==3.7.0
    - mpmath==1.3.0
    - networkx==3.1
    - numba==0.58.1
    - numexpr==2.8.6
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==13.580.82
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.5.82
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - nvitop==1.5.3
    - optuna==4.5.0
    - packaging==24.1
    - pandas==1.5.3
    - patool==1.12
    - pillow==10.4.0
    - platformdirs==4.2.2
    - prettytable==3.11.0
    - product-key-memory==0.1.10
    - protobuf==5.27.2
    - psutil==6.0.0
    - pydantic==2.8.2
    - pydantic-core==2.20.1
    - pynvml==11.5.3
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytorch-wavelets==1.3.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - reformer-pytorch==1.4.4
    - requests==2.32.3
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.13.2
    - sentry-sdk==2.8.0
    - setproctitle==1.3.3
    - six==1.16.0
    - sktime==0.16.1
    - smmap==5.0.1
    - sqlalchemy==2.0.43
    - sympy==1.11.1
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - toolz==0.12.1
    - torch==2.0.0
    - torch-timeseries==0.1.10
    - torchcde==0.2.5
    - torchdiffeq==0.2.4
    - torchmetrics==1.1.1
    - torchsde==0.2.6
    - torchtyping==0.1.4
    - torchvision==0.18.1
    - tqdm==4.64.1
    - trampoline==0.1.2
    - triton==2.0.0
    - tslearn==0.6.3
    - typeguard==4.3.0
    - typing-extensions==4.12.2
    - urllib3==2.2.2
    - wandb==0.17.4
    - wcwidth==0.2.13
    - wrapt==1.16.0
    - yacs==0.1.8
    - zipp==3.19.2
prefix: /new_home/Software/anaconda3/zh
